SRCDIR=./src/
OUTDIR=./builds/
LOGDIR=./logs/
MODELDIR=./PHOLD/
CC=6g
LD=6l -e
RM=rm -f
CD=cd
ECHO=echo -e \\t
MAKEALL=make all
SUCCMSG=Build completed 
CLEANMSG=Objects cleaned
LOGMSG=Logs cleaned
.SILENT :
